const data = [
  { iso: 'AF', iso3: 'AFG', name: 'AFGHANISTAN', phone_code: 93 },
  { iso: 'AL', iso3: 'ALB', name: 'ALBANIA', phone_code: 355 },
  { iso: 'DZ', iso3: 'DZA', name: 'ALGERIA', phone_code: 213 },
  { iso: 'AS', iso3: 'ASM', name: 'AMERICAN SAMOA', phone_code: 1684 },
  { iso: 'AD', iso3: 'AND', name: 'ANDORRA', phone_code: 376 },
  { iso: 'AO', iso3: 'AGO', name: 'ANGOLA', phone_code: 244 },
  { iso: 'AI', iso3: 'AIA', name: 'ANGUILLA', phone_code: 1264 },
  { iso: 'AQ', iso3: null, name: 'ANTARCTICA', phone_code: 0 },
  { iso: 'AG', iso3: 'ATG', name: 'ANTIGUA AND BARBUDA', phone_code: 1268 },
  { iso: 'AR', iso3: 'ARG', name: 'ARGENTINA', phone_code: 54 },
  { iso: 'AM', iso3: 'ARM', name: 'ARMENIA', phone_code: 374 },
  { iso: 'AW', iso3: 'ABW', name: 'ARUBA', phone_code: 297 },
  { iso: 'AU', iso3: 'AUS', name: 'AUSTRALIA', phone_code: 61 },
  { iso: 'AT', iso3: 'AUT', name: 'AUSTRIA', phone_code: 43 },
  { iso: 'AZ', iso3: 'AZE', name: 'AZERBAIJAN', phone_code: 994 },
  { iso: 'BS', iso3: 'BHS', name: 'BAHAMAS', phone_code: 1242 },
  { iso: 'BH', iso3: 'BHR', name: 'BAHRAIN', phone_code: 973 },
  { iso: 'BD', iso3: 'BGD', name: 'BANGLADESH', phone_code: 880 },
  { iso: 'BB', iso3: 'BRB', name: 'BARBADOS', phone_code: 1246 },
  { iso: 'BY', iso3: 'BLR', name: 'BELARUS', phone_code: 375 },
  { iso: 'BE', iso3: 'BEL', name: 'BELGIUM', phone_code: 32 },
  { iso: 'BZ', iso3: 'BLZ', name: 'BELIZE', phone_code: 501 },
  { iso: 'BJ', iso3: 'BEN', name: 'BENIN', phone_code: 229 },
  { iso: 'BM', iso3: 'BMU', name: 'BERMUDA', phone_code: 1441 },
  { iso: 'BT', iso3: 'BTN', name: 'BHUTAN', phone_code: 975 },
  { iso: 'BO', iso3: 'BOL', name: 'BOLIVIA', phone_code: 591 },
  { iso: 'BA', iso3: 'BIH', name: 'BOSNIA AND HERZEGOVINA', phone_code: 387 },
  { iso: 'BW', iso3: 'BWA', name: 'BOTSWANA', phone_code: 267 },
  { iso: 'BV', iso3: null, name: 'BOUVET ISLAND', phone_code: 0 },
  { iso: 'BR', iso3: 'BRA', name: 'BRAZIL', phone_code: 55 },
  { iso: 'IO', iso3: null, name: 'BRITISH INDIAN OCEAN TERRITORY', phone_code: 246 },
  { iso: 'BN', iso3: 'BRN', name: 'BRUNEI DARUSSALAM', phone_code: 673 },
  { iso: 'BG', iso3: 'BGR', name: 'BULGARIA', phone_code: 359 },
  { iso: 'BF', iso3: 'BFA', name: 'BURKINA FASO', phone_code: 226 },
  { iso: 'BI', iso3: 'BDI', name: 'BURUNDI', phone_code: 257 },
  { iso: 'KH', iso3: 'KHM', name: 'CAMBODIA', phone_code: 855 },
  { iso: 'CM', iso3: 'CMR', name: 'CAMEROON', phone_code: 237 },
  { iso: 'CA', iso3: 'CAN', name: 'CANADA', phone_code: 1 },
  { iso: 'CV', iso3: 'CPV', name: 'CAPE VERDE', phone_code: 238 },
  { iso: 'KY', iso3: 'CYM', name: 'CAYMAN ISLANDS', phone_code: 1345 },
  { iso: 'CF', iso3: 'CAF', name: 'CENTRAL AFRICAN REPUBLIC', phone_code: 236 },
  { iso: 'TD', iso3: 'TCD', name: 'CHAD', phone_code: 235 },
  { iso: 'CL', iso3: 'CHL', name: 'CHILE', phone_code: 56 },
  { iso: 'CN', iso3: 'CHN', name: 'CHINA', phone_code: 86 },
  { iso: 'CX', iso3: null, name: 'CHRISTMAS ISLAND', phone_code: 61 },
  { iso: 'CC', iso3: null, name: 'COCOS (KEELING) ISLANDS', phone_code: 672 },
  { iso: 'CO', iso3: 'COL', name: 'COLOMBIA', phone_code: 57 },
  { iso: 'KM', iso3: 'COM', name: 'COMOROS', phone_code: 269 },
  { iso: 'CG', iso3: 'COG', name: 'CONGO', phone_code: 242 },
  { iso: 'CD', iso3: 'COD', name: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', phone_code: 242 },
  { iso: 'CK', iso3: 'COK', name: 'COOK ISLANDS', phone_code: 682 },
  { iso: 'CR', iso3: 'CRI', name: 'COSTA RICA', phone_code: 506 },
  { iso: 'CI', iso3: 'CIV', name: "COTE D'IVOIRE", phone_code: 225 },
  { iso: 'HR', iso3: 'HRV', name: 'CROATIA', phone_code: 385 },
  { iso: 'CU', iso3: 'CUB', name: 'CUBA', phone_code: 53 },
  { iso: 'CY', iso3: 'CYP', name: 'CYPRUS', phone_code: 357 },
  { iso: 'CZ', iso3: 'CZE', name: 'CZECH REPUBLIC', phone_code: 420 },
  { iso: 'DK', iso3: 'DNK', name: 'DENMARK', phone_code: 45 },
  { iso: 'DJ', iso3: 'DJI', name: 'DJIBOUTI', phone_code: 253 },
  { iso: 'DM', iso3: 'DMA', name: 'DOMINICA', phone_code: 1767 },
  { iso: 'DO', iso3: 'DOM', name: 'DOMINICAN REPUBLIC', phone_code: 1809 },
  { iso: 'EC', iso3: 'ECU', name: 'ECUADOR', phone_code: 593 },
  { iso: 'EG', iso3: 'EGY', name: 'EGYPT', phone_code: 20 },
  { iso: 'SV', iso3: 'SLV', name: 'EL SALVADOR', phone_code: 503 },
  { iso: 'GQ', iso3: 'GNQ', name: 'EQUATORIAL GUINEA', phone_code: 240 },
  { iso: 'ER', iso3: 'ERI', name: 'ERITREA', phone_code: 291 },
  { iso: 'EE', iso3: 'EST', name: 'ESTONIA', phone_code: 372 },
  { iso: 'ET', iso3: 'ETH', name: 'ETHIOPIA', phone_code: 251 },
  { iso: 'FK', iso3: 'FLK', name: 'FALKLAND ISLANDS (MALVINAS)', phone_code: 500 },
  { iso: 'FO', iso3: 'FRO', name: 'FAROE ISLANDS', phone_code: 298 },
  { iso: 'FJ', iso3: 'FJI', name: 'FIJI', phone_code: 679 },
  { iso: 'FI', iso3: 'FIN', name: 'FINLAND', phone_code: 358 },
  { iso: 'FR', iso3: 'FRA', name: 'FRANCE', phone_code: 33 },
  { iso: 'GF', iso3: 'GUF', name: 'FRENCH GUIANA', phone_code: 594 },
  { iso: 'PF', iso3: 'PYF', name: 'FRENCH POLYNESIA', phone_code: 689 },
  { iso: 'TF', iso3: null, name: 'FRENCH SOUTHERN TERRITORIES', phone_code: 0 },
  { iso: 'GA', iso3: 'GAB', name: 'GABON', phone_code: 241 },
  { iso: 'GM', iso3: 'GMB', name: 'GAMBIA', phone_code: 220 },
  { iso: 'GE', iso3: 'GEO', name: 'GEORGIA', phone_code: 995 },
  { iso: 'DE', iso3: 'DEU', name: 'GERMANY', phone_code: 49 },
  { iso: 'GH', iso3: 'GHA', name: 'GHANA', phone_code: 233 },
  { iso: 'GI', iso3: 'GIB', name: 'GIBRALTAR', phone_code: 350 },
  { iso: 'GR', iso3: 'GRC', name: 'GREECE', phone_code: 30 },
  { iso: 'GL', iso3: 'GRL', name: 'GREENLAND', phone_code: 299 },
  { iso: 'GD', iso3: 'GRD', name: 'GRENADA', phone_code: 1473 },
  { iso: 'GP', iso3: 'GLP', name: 'GUADELOUPE', phone_code: 590 },
  { iso: 'GU', iso3: 'GUM', name: 'GUAM', phone_code: 1671 },
  { iso: 'GT', iso3: 'GTM', name: 'GUATEMALA', phone_code: 502 },
  { iso: 'GN', iso3: 'GIN', name: 'GUINEA', phone_code: 224 },
  { iso: 'GW', iso3: 'GNB', name: 'GUINEA-BISSAU', phone_code: 245 },
  { iso: 'GY', iso3: 'GUY', name: 'GUYANA', phone_code: 592 },
  { iso: 'HT', iso3: 'HTI', name: 'HAITI', phone_code: 509 },
  { iso: 'HM', iso3: null, name: 'HEARD ISLAND AND MCDONALD ISLANDS', phone_code: 0 },
  { iso: 'VA', iso3: 'VAT', name: 'HOLY SEE (VATICAN CITY STATE)', phone_code: 39 },
  { iso: 'HN', iso3: 'HND', name: 'HONDURAS', phone_code: 504 },
  { iso: 'HK', iso3: 'HKG', name: 'HONG KONG', phone_code: 852 },
  { iso: 'HU', iso3: 'HUN', name: 'HUNGARY', phone_code: 36 },
  { iso: 'IS', iso3: 'ISL', name: 'ICELAND', phone_code: 354 },
  { iso: 'IN', iso3: 'IND', name: 'INDIA', phone_code: 91 },
  { iso: 'ID', iso3: 'IDN', name: 'INDONESIA', phone_code: 62 },
  { iso: 'IR', iso3: 'IRN', name: 'IRAN, ISLAMIC REPUBLIC OF', phone_code: 98 },
  { iso: 'IQ', iso3: 'IRQ', name: 'IRAQ', phone_code: 964 },
  { iso: 'IE', iso3: 'IRL', name: 'IRELAND', phone_code: 353 },
  { iso: 'IL', iso3: 'ISR', name: 'ISRAEL', phone_code: 972 },
  { iso: 'IT', iso3: 'ITA', name: 'ITALY', phone_code: 39 },
  { iso: 'JM', iso3: 'JAM', name: 'JAMAICA', phone_code: 1876 },
  { iso: 'JP', iso3: 'JPN', name: 'JAPAN', phone_code: 81 },
  { iso: 'JO', iso3: 'JOR', name: 'JORDAN', phone_code: 962 },
  { iso: 'KZ', iso3: 'KAZ', name: 'KAZAKHSTAN', phone_code: 7 },
  { iso: 'KE', iso3: 'KEN', name: 'KENYA', phone_code: 254 },
  { iso: 'KI', iso3: 'KIR', name: 'KIRIBATI', phone_code: 686 },
  { iso: 'KP', iso3: 'PRK', name: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", phone_code: 850 },
  { iso: 'KR', iso3: 'KOR', name: 'KOREA, REPUBLIC OF', phone_code: 82 },
  { iso: 'KW', iso3: 'KWT', name: 'KUWAIT', phone_code: 965 },
  { iso: 'KG', iso3: 'KGZ', name: 'KYRGYZSTAN', phone_code: 996 },
  { iso: 'LA', iso3: 'LAO', name: "LAO PEOPLE'S DEMOCRATIC REPUBLIC", phone_code: 856 },
  { iso: 'LV', iso3: 'LVA', name: 'LATVIA', phone_code: 371 },
  { iso: 'LB', iso3: 'LBN', name: 'LEBANON', phone_code: 961 },
  { iso: 'LS', iso3: 'LSO', name: 'LESOTHO', phone_code: 266 },
  { iso: 'LR', iso3: 'LBR', name: 'LIBERIA', phone_code: 231 },
  { iso: 'LY', iso3: 'LBY', name: 'LIBYAN ARAB JAMAHIRIYA', phone_code: 218 },
  { iso: 'LI', iso3: 'LIE', name: 'LIECHTENSTEIN', phone_code: 423 },
  { iso: 'LT', iso3: 'LTU', name: 'LITHUANIA', phone_code: 370 },
  { iso: 'LU', iso3: 'LUX', name: 'LUXEMBOURG', phone_code: 352 },
  { iso: 'MO', iso3: 'MAC', name: 'MACAO', phone_code: 853 },
  { iso: 'MK', iso3: 'MKD', name: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', phone_code: 389 },
  { iso: 'MG', iso3: 'MDG', name: 'MADAGASCAR', phone_code: 261 },
  { iso: 'MW', iso3: 'MWI', name: 'MALAWI', phone_code: 265 },
  { iso: 'MY', iso3: 'MYS', name: 'MALAYSIA', phone_code: 60 },
  { iso: 'MV', iso3: 'MDV', name: 'MALDIVES', phone_code: 960 },
  { iso: 'ML', iso3: 'MLI', name: 'MALI', phone_code: 223 },
  { iso: 'MT', iso3: 'MLT', name: 'MALTA', phone_code: 356 },
  { iso: 'MH', iso3: 'MHL', name: 'MARSHALL ISLANDS', phone_code: 692 },
  { iso: 'MQ', iso3: 'MTQ', name: 'MARTINIQUE', phone_code: 596 },
  { iso: 'MR', iso3: 'MRT', name: 'MAURITANIA', phone_code: 222 },
  { iso: 'MU', iso3: 'MUS', name: 'MAURITIUS', phone_code: 230 },
  { iso: 'YT', iso3: null, name: 'MAYOTTE', phone_code: 269 },
  { iso: 'MX', iso3: 'MEX', name: 'MEXICO', phone_code: 52 },
  { iso: 'FM', iso3: 'FSM', name: 'MICRONESIA, FEDERATED STATES OF', phone_code: 691 },
  { iso: 'MD', iso3: 'MDA', name: 'MOLDOVA, REPUBLIC OF', phone_code: 373 },
  { iso: 'MC', iso3: 'MCO', name: 'MONACO', phone_code: 377 },
  { iso: 'MN', iso3: 'MNG', name: 'MONGOLIA', phone_code: 976 },
  { iso: 'MS', iso3: 'MSR', name: 'MONTSERRAT', phone_code: 1664 },
  { iso: 'MA', iso3: 'MAR', name: 'MOROCCO', phone_code: 212 },
  { iso: 'MZ', iso3: 'MOZ', name: 'MOZAMBIQUE', phone_code: 258 },
  { iso: 'MM', iso3: 'MMR', name: 'MYANMAR', phone_code: 95 },
  { iso: 'NA', iso3: 'NAM', name: 'NAMIBIA', phone_code: 264 },
  { iso: 'NR', iso3: 'NRU', name: 'NAURU', phone_code: 674 },
  { iso: 'NP', iso3: 'NPL', name: 'NEPAL', phone_code: 977 },
  { iso: 'NL', iso3: 'NLD', name: 'NETHERLANDS', phone_code: 31 },
  { iso: 'AN', iso3: 'ANT', name: 'NETHERLANDS ANTILLES', phone_code: 599 },
  { iso: 'NC', iso3: 'NCL', name: 'NEW CALEDONIA', phone_code: 687 },
  { iso: 'NZ', iso3: 'NZL', name: 'NEW ZEALAND', phone_code: 64 },
  { iso: 'NI', iso3: 'NIC', name: 'NICARAGUA', phone_code: 505 },
  { iso: 'NE', iso3: 'NER', name: 'NIGER', phone_code: 227 },
  { iso: 'NG', iso3: 'NGA', name: 'NIGERIA', phone_code: 234 },
  { iso: 'NU', iso3: 'NIU', name: 'NIUE', phone_code: 683 },
  { iso: 'NF', iso3: 'NFK', name: 'NORFOLK ISLAND', phone_code: 672 },
  { iso: 'MP', iso3: 'MNP', name: 'NORTHERN MARIANA ISLANDS', phone_code: 1670 },
  { iso: 'NO', iso3: 'NOR', name: 'NORWAY', phone_code: 47 },
  { iso: 'OM', iso3: 'OMN', name: 'OMAN', phone_code: 968 },
  { iso: 'PK', iso3: 'PAK', name: 'PAKISTAN', phone_code: 92 },
  { iso: 'PW', iso3: 'PLW', name: 'PALAU', phone_code: 680 },
  { iso: 'PS', iso3: null, name: 'PALESTINIAN TERRITORY, OCCUPIED', phone_code: 970 },
  { iso: 'PA', iso3: 'PAN', name: 'PANAMA', phone_code: 507 },
  { iso: 'PG', iso3: 'PNG', name: 'PAPUA NEW GUINEA', phone_code: 675 },
  { iso: 'PY', iso3: 'PRY', name: 'PARAGUAY', phone_code: 595 },
  { iso: 'PE', iso3: 'PER', name: 'PERU', phone_code: 51 },
  { iso: 'PH', iso3: 'PHL', name: 'PHILIPPINES', phone_code: 63 },
  { iso: 'PN', iso3: 'PCN', name: 'PITCAIRN', phone_code: 0 },
  { iso: 'PL', iso3: 'POL', name: 'POLAND', phone_code: 48 },
  { iso: 'PT', iso3: 'PRT', name: 'PORTUGAL', phone_code: 351 },
  { iso: 'PR', iso3: 'PRI', name: 'PUERTO RICO', phone_code: 1787 },
  { iso: 'QA', iso3: 'QAT', name: 'QATAR', phone_code: 974 },
  { iso: 'RE', iso3: 'REU', name: 'REUNION', phone_code: 262 },
  { iso: 'RO', iso3: 'ROM', name: 'ROMANIA', phone_code: 40 },
  { iso: 'RU', iso3: 'RUS', name: 'RUSSIAN FEDERATION', phone_code: 70 },
  { iso: 'RW', iso3: 'RWA', name: 'RWANDA', phone_code: 250 },
  { iso: 'SH', iso3: 'SHN', name: 'SAINT HELENA', phone_code: 290 },
  { iso: 'KN', iso3: 'KNA', name: 'SAINT KITTS AND NEVIS', phone_code: 1869 },
  { iso: 'LC', iso3: 'LCA', name: 'SAINT LUCIA', phone_code: 1758 },
  { iso: 'PM', iso3: 'SPM', name: 'SAINT PIERRE AND MIQUELON', phone_code: 508 },
  { iso: 'VC', iso3: 'VCT', name: 'SAINT VINCENT AND THE GRENADINES', phone_code: 1784 },
  { iso: 'WS', iso3: 'WSM', name: 'SAMOA', phone_code: 684 },
  { iso: 'SM', iso3: 'SMR', name: 'SAN MARINO', phone_code: 378 },
  { iso: 'ST', iso3: 'STP', name: 'SAO TOME AND PRINCIPE', phone_code: 239 },
  { iso: 'SA', iso3: 'SAU', name: 'SAUDI ARABIA', phone_code: 966 },
  { iso: 'SN', iso3: 'SEN', name: 'SENEGAL', phone_code: 221 },
  { iso: 'CS', iso3: null, name: 'SERBIA AND MONTENEGRO', phone_code: 381 },
  { iso: 'SC', iso3: 'SYC', name: 'SEYCHELLES', phone_code: 248 },
  { iso: 'SL', iso3: 'SLE', name: 'SIERRA LEONE', phone_code: 232 },
  { iso: 'SG', iso3: 'SGP', name: 'SINGAPORE', phone_code: 65 },
  { iso: 'SK', iso3: 'SVK', name: 'SLOVAKIA', phone_code: 421 },
  { iso: 'SI', iso3: 'SVN', name: 'SLOVENIA', phone_code: 386 },
  { iso: 'SB', iso3: 'SLB', name: 'SOLOMON ISLANDS', phone_code: 677 },
  { iso: 'SO', iso3: 'SOM', name: 'SOMALIA', phone_code: 252 },
  { iso: 'ZA', iso3: 'ZAF', name: 'SOUTH AFRICA', phone_code: 27 },
  { iso: 'GS', iso3: null, name: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', phone_code: 0 },
  { iso: 'ES', iso3: 'ESP', name: 'SPAIN', phone_code: 34 },
  { iso: 'LK', iso3: 'LKA', name: 'SRI LANKA', phone_code: 94 },
  { iso: 'SD', iso3: 'SDN', name: 'SUDAN', phone_code: 249 },
  { iso: 'SR', iso3: 'SUR', name: 'SURINAME', phone_code: 597 },
  { iso: 'SJ', iso3: 'SJM', name: 'SVALBARD AND JAN MAYEN', phone_code: 47 },
  { iso: 'SZ', iso3: 'SWZ', name: 'SWAZILAND', phone_code: 268 },
  { iso: 'SE', iso3: 'SWE', name: 'SWEDEN', phone_code: 46 },
  { iso: 'CH', iso3: 'CHE', name: 'SWITZERLAND', phone_code: 41 },
  { iso: 'SY', iso3: 'SYR', name: 'SYRIAN ARAB REPUBLIC', phone_code: 963 },
  { iso: 'TW', iso3: 'TWN', name: 'TAIWAN, PROVINCE OF CHINA', phone_code: 886 },
  { iso: 'TJ', iso3: 'TJK', name: 'TAJIKISTAN', phone_code: 992 },
  { iso: 'TZ', iso3: 'TZA', name: 'TANZANIA, UNITED REPUBLIC OF', phone_code: 255 },
  { iso: 'TH', iso3: 'THA', name: 'THAILAND', phone_code: 66 },
  { iso: 'TL', iso3: null, name: 'TIMOR-LESTE', phone_code: 670 },
  { iso: 'TG', iso3: 'TGO', name: 'TOGO', phone_code: 228 },
  { iso: 'TK', iso3: 'TKL', name: 'TOKELAU', phone_code: 690 },
  { iso: 'TO', iso3: 'TON', name: 'TONGA', phone_code: 676 },
  { iso: 'TT', iso3: 'TTO', name: 'TRINIDAD AND TOBAGO', phone_code: 1868 },
  { iso: 'TN', iso3: 'TUN', name: 'TUNISIA', phone_code: 216 },
  { iso: 'TR', iso3: 'TUR', name: 'TURKEY', phone_code: 90 },
  { iso: 'TM', iso3: 'TKM', name: 'TURKMENISTAN', phone_code: 7370 },
  { iso: 'TC', iso3: 'TCA', name: 'TURKS AND CAICOS ISLANDS', phone_code: 1649 },
  { iso: 'TV', iso3: 'TUV', name: 'TUVALU', phone_code: 688 },
  { iso: 'UG', iso3: 'UGA', name: 'UGANDA', phone_code: 256 },
  { iso: 'UA', iso3: 'UKR', name: 'UKRAINE', phone_code: 380 },
  { iso: 'AE', iso3: 'ARE', name: 'UNITED ARAB EMIRATES', phone_code: 971 },
  { iso: 'GB', iso3: 'GBR', name: 'UNITED KINGDOM', phone_code: 44 },
  { iso: 'US', iso3: 'USA', name: 'UNITED STATES', phone_code: 1 },
  { iso: 'UM', iso3: null, name: 'UNITED STATES MINOR OUTLYING ISLANDS', phone_code: 1 },
  { iso: 'UY', iso3: 'URY', name: 'URUGUAY', phone_code: 598 },
  { iso: 'UZ', iso3: 'UZB', name: 'UZBEKISTAN', phone_code: 998 },
  { iso: 'VU', iso3: 'VUT', name: 'VANUATU', phone_code: 678 },
  { iso: 'VE', iso3: 'VEN', name: 'VENEZUELA', phone_code: 58 },
  { iso: 'VN', iso3: 'VNM', name: 'VIET NAM', phone_code: 84 },
  { iso: 'VG', iso3: 'VGB', name: 'VIRGIN ISLANDS, BRITISH', phone_code: 1284 },
  { iso: 'VI', iso3: 'VIR', name: 'VIRGIN ISLANDS, U.S.', phone_code: 1340 },
  { iso: 'WF', iso3: 'WLF', name: 'WALLIS AND FUTUNA', phone_code: 681 },
  { iso: 'EH', iso3: 'ESH', name: 'WESTERN SAHARA', phone_code: 212 },
  { iso: 'YE', iso3: 'YEM', name: 'YEMEN', phone_code: 967 },
  { iso: 'ZM', iso3: 'ZMB', name: 'ZAMBIA', phone_code: 260 },
  { iso: 'ZW', iso3: 'ZWE', name: 'ZIMBABWE', phone_code: 263 },
];

async function seed(prisma) {
  const count = await prisma.countries.count();
  if (count > 0) {
    console.log(`  countries: ya tiene ${count} registros, omitido`);
    return;
  }
  await prisma.countries.createMany({ data });
  console.log(`  countries: ${data.length} registros creados`);
}

module.exports = seed;
