const data = [
  // Canada (13)
  { name: 'Alberta', country: 'CA', iso: 'AB', iso3: 'ALB', zip: 'T0A' },
  { name: 'British Columbia', country: 'CA', iso: 'BC', iso3: 'BRC', zip: 'V0A' },
  { name: 'Manitoba', country: 'CA', iso: 'MB', iso3: 'MAN', zip: 'R0A' },
  { name: 'New Brunswick', country: 'CA', iso: 'NB', iso3: 'NBR', zip: 'E2A' },
  { name: 'Newfoundland and Labrador', country: 'CA', iso: 'NL', iso3: 'NFL', zip: 'A0A' },
  { name: 'Northwest Territories', country: 'CA', iso: 'NT', iso3: 'NWT', zip: 'X0E' },
  { name: 'Nova Scotia', country: 'CA', iso: 'NS', iso3: 'NSC', zip: 'B0A' },
  { name: 'Nunavut', country: 'CA', iso: 'NU', iso3: 'NUN', zip: 'X0A' },
  { name: 'Ontario', country: 'CA', iso: 'ON', iso3: 'ONT', zip: 'K0A' },
  { name: 'Prince Edward Island', country: 'CA', iso: 'PE', iso3: 'PEI', zip: 'C0A' },
  { name: 'Quebec', country: 'CA', iso: 'QC', iso3: 'QUE', zip: 'G0A' },
  { name: 'Saskatchewan', country: 'CA', iso: 'SK', iso3: 'SAS', zip: 'S0A' },
  { name: 'Yukon', country: 'CA', iso: 'YT', iso3: 'YUK', zip: 'Y1A' },
  // Colombia (33)
  { name: 'Amazonas', country: 'CO', iso: 'AMA', iso3: 'AMA', zip: '91' },
  { name: 'Antioquia', country: 'CO', iso: 'ANT', iso3: 'ANT', zip: '05' },
  { name: 'Arauca', country: 'CO', iso: 'ARA', iso3: 'ARA', zip: '81' },
  { name: 'Atlántico', country: 'CO', iso: 'ATL', iso3: 'ATL', zip: '08' },
  { name: 'Bolívar', country: 'CO', iso: 'BOL', iso3: 'BOL', zip: '13' },
  { name: 'Boyacá', country: 'CO', iso: 'BOY', iso3: 'BOY', zip: '15' },
  { name: 'Caldas', country: 'CO', iso: 'CAL', iso3: 'CAL', zip: '17' },
  { name: 'Caquetá', country: 'CO', iso: 'CAQ', iso3: 'CAQ', zip: '18' },
  { name: 'Casanare', country: 'CO', iso: 'CAS', iso3: 'CAS', zip: '85' },
  { name: 'Cauca', country: 'CO', iso: 'CAU', iso3: 'CAU', zip: '19' },
  { name: 'Cesar', country: 'CO', iso: 'CES', iso3: 'CES', zip: '20' },
  { name: 'Chocó', country: 'CO', iso: 'CHO', iso3: 'CHO', zip: '27' },
  { name: 'Cundinamarca', country: 'CO', iso: 'CUN', iso3: 'CUN', zip: '25' },
  { name: 'Córdoba', country: 'CO', iso: 'COR', iso3: 'COR', zip: '23' },
  { name: 'Distrito Capital de Bogotá', country: 'CO', iso: 'DC', iso3: 'DC', zip: '11' },
  { name: 'Guainía', country: 'CO', iso: 'GUA', iso3: 'GUA', zip: '94' },
  { name: 'Guaviare', country: 'CO', iso: 'GUV', iso3: 'GUV', zip: '97' },
  { name: 'Huila', country: 'CO', iso: 'HUI', iso3: 'HUI', zip: '41' },
  { name: 'La Guajira', country: 'CO', iso: 'LAG', iso3: 'LAG', zip: '44' },
  { name: 'Magdalena', country: 'CO', iso: 'MAG', iso3: 'MAG', zip: '47' },
  { name: 'Meta', country: 'CO', iso: 'MET', iso3: 'MET', zip: '50' },
  { name: 'Nariño', country: 'CO', iso: 'NAR', iso3: 'NAR', zip: '52' },
  { name: 'Norte de Santander', country: 'CO', iso: 'NSA', iso3: 'NSA', zip: '54' },
  { name: 'Putumayo', country: 'CO', iso: 'PUT', iso3: 'PUT', zip: '86' },
  { name: 'Quindío', country: 'CO', iso: 'QUI', iso3: 'QUI', zip: '63' },
  { name: 'Risaralda', country: 'CO', iso: 'RIS', iso3: 'RIS', zip: '66' },
  { name: 'San Andrés y Providencia', country: 'CO', iso: 'SAP', iso3: 'SAP', zip: '88' },
  { name: 'Santander', country: 'CO', iso: 'SAN', iso3: 'SAN', zip: '68' },
  { name: 'Sucre', country: 'CO', iso: 'SUC', iso3: 'SUC', zip: '70' },
  { name: 'Tolima', country: 'CO', iso: 'TOL', iso3: 'TOL', zip: '73' },
  { name: 'Valle del Cauca', country: 'CO', iso: 'VAC', iso3: 'VAC', zip: '76' },
  { name: 'Vaupés', country: 'CO', iso: 'VAU', iso3: 'VAU', zip: '97' },
  { name: 'Vichada', country: 'CO', iso: 'VID', iso3: 'VID', zip: '99' },
  // United States (50)
  { name: 'Alabama', country: 'US', iso: 'AL', iso3: 'ALA', zip: '35004' },
  { name: 'Alaska', country: 'US', iso: 'AK', iso3: 'ALK', zip: '99501' },
  { name: 'Arizona', country: 'US', iso: 'AZ', iso3: 'ARZ', zip: '85001' },
  { name: 'Arkansas', country: 'US', iso: 'AR', iso3: 'ARK', zip: '71601' },
  { name: 'California', country: 'US', iso: 'CA', iso3: 'CAL', zip: '90001' },
  { name: 'Colorado', country: 'US', iso: 'CO', iso3: 'COL', zip: '80001' },
  { name: 'Connecticut', country: 'US', iso: 'CT', iso3: 'CON', zip: '6001' },
  { name: 'Delaware', country: 'US', iso: 'DE', iso3: 'DEL', zip: '19701' },
  { name: 'Florida', country: 'US', iso: 'FL', iso3: 'FLA', zip: '32003' },
  { name: 'Georgia', country: 'US', iso: 'GA', iso3: 'GEO', zip: '30002' },
  { name: 'Hawaii', country: 'US', iso: 'HI', iso3: 'HAW', zip: '96701' },
  { name: 'Idaho', country: 'US', iso: 'ID', iso3: 'IDA', zip: '83201' },
  { name: 'Illinois', country: 'US', iso: 'IL', iso3: 'ILL', zip: '60001' },
  { name: 'Indiana', country: 'US', iso: 'IN', iso3: 'IND', zip: '46001' },
  { name: 'Iowa', country: 'US', iso: 'IA', iso3: 'IOW', zip: '50001' },
  { name: 'Kansas', country: 'US', iso: 'KS', iso3: 'KAN', zip: '66002' },
  { name: 'Kentucky', country: 'US', iso: 'KY', iso3: 'KEN', zip: '40003' },
  { name: 'Louisiana', country: 'US', iso: 'LA', iso3: 'LOU', zip: '70001' },
  { name: 'Maine', country: 'US', iso: 'ME', iso3: 'MAI', zip: '3901' },
  { name: 'Maryland', country: 'US', iso: 'MD', iso3: 'MAR', zip: '20601' },
  { name: 'Massachusetts', country: 'US', iso: 'MA', iso3: 'MAS', zip: '1001' },
  { name: 'Michigan', country: 'US', iso: 'MI', iso3: 'MIC', zip: '48001' },
  { name: 'Minnesota', country: 'US', iso: 'MN', iso3: 'MIN', zip: '55001' },
  { name: 'Mississippi', country: 'US', iso: 'MS', iso3: 'MIS', zip: '38601' },
  { name: 'Missouri', country: 'US', iso: 'MO', iso3: 'MOU', zip: '63001' },
  { name: 'Montana', country: 'US', iso: 'MT', iso3: 'MON', zip: '59001' },
  { name: 'Nebraska', country: 'US', iso: 'NE', iso3: 'NEB', zip: '68001' },
  { name: 'Nevada', country: 'US', iso: 'NV', iso3: 'NEV', zip: '88901' },
  { name: 'New Hampshire', country: 'US', iso: 'NH', iso3: 'NHA', zip: '3031' },
  { name: 'New Jersey', country: 'US', iso: 'NJ', iso3: 'NJE', zip: '7001' },
  { name: 'New Mexico', country: 'US', iso: 'NM', iso3: 'NME', zip: '87001' },
  { name: 'New York', country: 'US', iso: 'NY', iso3: 'NYO', zip: '10001' },
  { name: 'North Carolina', country: 'US', iso: 'NC', iso3: 'NCA', zip: '27006' },
  { name: 'North Dakota', country: 'US', iso: 'ND', iso3: 'NDA', zip: '58001' },
  { name: 'Ohio', country: 'US', iso: 'OH', iso3: 'OHI', zip: '43001' },
  { name: 'Oklahoma', country: 'US', iso: 'OK', iso3: 'OKL', zip: '73001' },
  { name: 'Oregon', country: 'US', iso: 'OR', iso3: 'ORE', zip: '97001' },
  { name: 'Pennsylvania', country: 'US', iso: 'PA', iso3: 'PEN', zip: '15001' },
  { name: 'Rhode Island', country: 'US', iso: 'RI', iso3: 'RHO', zip: '2801' },
  { name: 'South Carolina', country: 'US', iso: 'SC', iso3: 'SCA', zip: '29001' },
  { name: 'South Dakota', country: 'US', iso: 'SD', iso3: 'SDA', zip: '57001' },
  { name: 'Tennessee', country: 'US', iso: 'TN', iso3: 'TEN', zip: '37010' },
  { name: 'Texas', country: 'US', iso: 'TX', iso3: 'TEX', zip: '73301' },
  { name: 'Utah', country: 'US', iso: 'UT', iso3: 'UTA', zip: '84001' },
  { name: 'Vermont', country: 'US', iso: 'VT', iso3: 'VER', zip: '5001' },
  { name: 'Virginia', country: 'US', iso: 'VA', iso3: 'VIR', zip: '20101' },
  { name: 'Washington', country: 'US', iso: 'WA', iso3: 'WAS', zip: '98001' },
  { name: 'West Virginia', country: 'US', iso: 'WV', iso3: 'WVI', zip: '24701' },
  { name: 'Wisconsin', country: 'US', iso: 'WI', iso3: 'WIS', zip: '53001' },
  { name: 'Wyoming', country: 'US', iso: 'WY', iso3: 'WYO', zip: '82001' },
];

async function seed(prisma) {
  const count = await prisma.states.count();
  if (count > 0) {
    console.log(`  states: ya tiene ${count} registros, omitido`);
    return;
  }
  await prisma.states.createMany({ data });
  console.log(`  states: ${data.length} registros creados`);
}

module.exports = seed;
