export default [
  {
    component: 'CNavTitle',
    name: 'Inicio',
  },
  {
    component: 'CNavItem',
    name: 'Próximos',
    to: '/next',
    icon: 'cil-arrow-right',
    permission: 'accommodations:view',
  },
  {
    component: 'CNavItem',
    name: 'Disponibilidad',
    to: '/availability',
    icon: 'cil-check-circle',
    permission: 'accommodations:view',
  },
  {
    component: 'CNavTitle',
    name: 'Análisis',
    permission: 'analytics:view',
  },
  {
    component: 'CNavItem',
    name: 'Análisis de Hospedajes',
    to: '/dashboard',
    icon: 'cil-home',
    permission: 'analytics:view',
  },
  {
    component: 'CNavItem',
    name: 'Análisis Financiero',
    to: '/analytics',
    icon: 'cil-chart-pie',
    permission: 'analytics:view',
  },
  {
    component: 'CNavTitle',
    name: 'Negocio',
  },
  {
    component: 'CNavItem',
    name: 'Cabañas',
    to: '/business/venues',
    icon: 'cil-location-pin',
    permission: 'venues:view',
  },
  {
    component: 'CNavItem',
    name: 'Contactos',
    to: '/business/contacts',
    icon: 'cil-user',
    permission: 'contacts:view',
  },
  {
    component: 'CNavItem',
    name: 'Cotizaciones',
    to: '/business/estimates',
    icon: 'cil-notes',
    permission: 'estimates:view',
  },
  {
    component: 'CNavItem',
    name: 'Hospedajes',
    to: '/business/accommodations',
    icon: 'cil-calendar',
    permission: 'accommodations:view',
  },
  {
    component: 'CNavItem',
    name: 'Organizaciones',
    to: '/business/organizations',
    icon: 'cil-briefcase',
    permission: 'organizations:view',
  },
  {
    component: 'CNavTitle',
    name: 'Contabilidad',
    permission: 'payments:view',
  },
  {
    component: 'CNavItem',
    name: 'Ingresos',
    to: '/business/payments',
    icon: 'cil-dollar',
    permission: 'payments:view',
  },
  {
    component: 'CNavItem',
    name: 'Egresos',
    to: '/business/expenses',
    icon: 'cil-cart',
    permission: 'expenses:view',
  },
  {
    component: 'CNavItem',
    name: 'Depósitos',
    to: '/business/deposits',
    icon: 'cil-wallet',
    permission: 'deposits:view',
  },
  {
    component: 'CNavItem',
    name: 'Comisionistas',
    to: '/business/commissions/agents',
    icon: 'cil-people',
    permission: 'commissions:view',
  },
  {
    component: 'CNavItem',
    name: 'Pagos Comisiones',
    to: '/business/commissions/payments',
    icon: 'cil-dollar',
    permission: 'commissions:view',
  },
  {
    component: 'CNavTitle',
    name: 'Inventario',
    permission: 'inventory:view',
  },
  {
    component: 'CNavItem',
    name: 'Insumos y Activos',
    to: '/business/inventory',
    icon: 'cil-clipboard',
    permission: 'inventory:view',
  },
  {
    component: 'CNavItem',
    name: 'Categorías',
    to: '/admin/inventory-categories',
    icon: 'cil-layers',
    permission: 'inventory:view',
  },
  {
    component: 'CNavTitle',
    name: 'Mantenimiento',
    permission: 'maintenance:view',
  },
  {
    component: 'CNavItem',
    name: 'Tareas Pendientes',
    to: '/business/pending-tasks',
    icon: 'cil-list',
    permission: 'maintenance:view',
  },
  {
    component: 'CNavItem',
    name: 'Tablero',
    to: '/business/maintenance',
    icon: 'cil-speedometer',
    permission: 'maintenance:view',
  },
  {
    component: 'CNavItem',
    name: 'Registros',
    to: '/business/maintenance/logs',
    icon: 'cil-task',
    permission: 'maintenance:view',
  },
  {
    component: 'CNavItem',
    name: 'Zonas',
    to: '/admin/maintenance-zones',
    icon: 'cil-map',
    permission: 'maintenance:view',
  },
  {
    component: 'CNavTitle',
    name: 'Sistema',
    permission: 'users:view',
  },
  {
    component: 'CNavItem',
    name: 'Usuarios',
    to: '/users',
    icon: 'cil-people',
    permission: 'users:view',
  },
  {
    component: 'CNavItem',
    name: 'Invitaciones',
    to: '/invitations',
    icon: 'cil-envelope-open',
    permission: 'invitations:view',
  },
  {
    component: 'CNavItem',
    name: 'Perfiles',
    to: '/admin/profiles',
    icon: 'cil-shield-alt',
    permission: 'profiles:view',
  },
  {
    component: 'CNavItem',
    name: 'Amenidades',
    to: '/admin/amenities',
    icon: 'cil-list-rich',
    permission: 'amenities:manage',
  },
  {
    component: 'CNavItem',
    name: 'Categorías de Gastos',
    to: '/admin/expense-categories',
    icon: 'cil-applications',
    permission: 'expenses:view',
  },
  {
    component: 'CNavItem',
    name: 'Templates de Mensajes',
    to: '/admin/message-templates',
    icon: 'cil-speech',
    permission: 'templates:manage',
  },
  {
    component: 'CNavItem',
    name: 'Configuración IA',
    to: '/admin/ai-settings',
    icon: 'cil-bolt',
    permission: 'ai:manage',
  },
  {
    component: 'CNavItem',
    name: 'Uso de IA',
    to: '/admin/ai-usage',
    icon: 'cil-chart',
    permission: 'ai:manage',
  },
  {
    component: 'CNavItem',
    name: 'WhatsApp Sistema',
    to: '/admin/system-whatsapp',
    icon: 'cil-phone',
    permission: 'whatsapp:manage',
  },
  {
    component: 'CNavItem',
    name: 'Configuración',
    to: '/settings',
    icon: 'cil-settings',
    permission: 'settings:view',
  },
]
